Q1

In [3]:
import numpy as np
import pandas as pd
arr = pd.read_csv("Iris.csv")


arr1 = arr.to_numpy()
print(arr1.dtype)
print(arr1.shape)
print(arr1[:5])

object
(150, 6)
[[1 5.1 3.5 1.4 0.2 'Iris-setosa']
 [2 4.9 3.0 1.4 0.2 'Iris-setosa']
 [3 4.7 3.2 1.3 0.2 'Iris-setosa']
 [4 4.6 3.1 1.5 0.2 'Iris-setosa']
 [5 5.0 3.6 1.4 0.2 'Iris-setosa']]


Q2

In [5]:
import pandas as pd
import numpy as np
arr = pd.read_csv("Iris.csv")

nf = arr.select_dtypes(include=[np.number])

mean =nf.mean(axis=0)
std =nf.std(axis=0)


standardized_nf = (nf - mean) / std


arr[nf.columns] = standardized_nf


arr1 = arr.to_numpy()


arr1


array([[-1.7147973061923394, -0.8976738791967661, 1.0286112808972343,
        -1.3367940202882493, -1.308592819437958, 'Iris-setosa'],
       [-1.6917798926864018, -1.1392004834649532, -0.12454037930145956,
        -1.3367940202882493, -1.308592819437958, 'Iris-setosa'],
       [-1.6687624791804645, -1.3807270877331412, 0.3367202847780184,
        -1.393469854952816, -1.308592819437958, 'Iris-setosa'],
       [-1.645745065674527, -1.5014903898672358, 0.10608995273827942,
        -1.2801181856236823, -1.308592819437958, 'Iris-setosa'],
       [-1.6227276521685896, -1.0184371813308597, 1.2592416129369732,
        -1.3367940202882493, -1.308592819437958, 'Iris-setosa'],
       [-1.599710238662652, -0.5353839727944832, 1.9511326090561893,
        -1.1667665162945489, -1.0465248315665376, 'Iris-setosa'],
       [-1.5766928251567147, -1.5014903898672358, 0.7979809488574954,
        -1.3367940202882493, -1.1775588255022478, 'Iris-setosa'],
       [-1.5536754116507772, -1.0184371813308597, 0.7

Q3

In [6]:
import pandas as pd
import numpy as np
arr = pd.read_csv("iris.csv")
nf = arr.select_dtypes(include=[np.number])
correlation_matrix = np.corrcoef(nf, rowvar=False)
correlation_matrix


array([[ 1.        ,  0.71667627, -0.39772881,  0.88274732,  0.89975858],
       [ 0.71667627,  1.        , -0.10936925,  0.87175416,  0.81795363],
       [-0.39772881, -0.10936925,  1.        , -0.4205161 , -0.35654409],
       [ 0.88274732,  0.87175416, -0.4205161 ,  1.        ,  0.9627571 ],
       [ 0.89975858,  0.81795363, -0.35654409,  0.9627571 ,  1.        ]])

Q4

In [7]:
import pandas as pd

In [8]:
df= pd.read_csv("Iris.csv")
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [9]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [10]:
df.duplicated().sum()

0

In [11]:
df.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [23]:
st = df["Species"].unique()
print(st)

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [24]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
df["Species"]=le.fit_transform(df["Species"])
df["Species"].unique()

array([0, 1, 2])

In [25]:
x = df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
y = df['Species']

In [26]:
x

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [27]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int32

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2,random_state=0)

In [29]:
print(x_train.head())
print(y_train.head())

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
137            6.4           3.1            5.5           1.8
84             5.4           3.0            4.5           1.5
27             5.2           3.5            1.5           0.2
127            6.1           3.0            4.9           1.8
132            6.4           2.8            5.6           2.2
137    2
84     1
27     0
127    2
132    2
Name: Species, dtype: int32


In [30]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import mean_absolute_error
kn=KNeighborsClassifier(n_neighbors=5)
kn.fit(x_test,y_test)
pred_y=kn.predict(x_test)
print(pred_y)
print(f"KNN : {mean_absolute_error (y_test,pred_y)}")

[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 1 0 0 1 1 0]
KNN : 0.03333333333333333


Q5
Not Perform